name: changeset
description: A lightweight CLI tool to manage changesets for Dart/Flutter projects.
version: 1.2.0
repository: https://github.com/emirchus/changeset

environment:
  sdk: ^3.9.2

dependencies:
  args: ^2.7.0
  yaml: ^3.1.2

executables:
  changeset: changeset

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6
